// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
export const parser = Parser.deserialize({
  version: 13,
  states: "bOVQPOOOOQO'#Ce'#CeQOQPOO",
  stateData: "h~OWOS~OQPORPOSPOTPOUXP~O",
  goto: "^YPPPPPPPPPZRQO",
  nodeNames: "⚠ Program Int Identifier String RightSide",
  maxTerm: 9,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "#d~RXXYnYZn]^npqnrs!P!Q![!n!]!^!v!c!}#R#T#o#R~sSW~XYnYZn]^npqn~!STOr!Prs!cs#O!P#O#P!h#P~!P~!hOS~~!kPO~!P~!sPQ~!Q![!n~!yP!Q!S!|~#ROT~~#WSR~!Q![#R!c!}#R#R#S#R#T#o#R",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
