[package]
name = "fibo-machine"
version = "0.1.0"
authors = ["tourtiere"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.0"
num-bigint = "0.4.0"